
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon Apr 06 18:10:09 CEST 2026
//----------------------------------------------------

package asint;

import java_cup.runtime.*;
import alex.AnalizadorLexicoMilu;
import alex.UnidadLexica;
import errors.GestionErroresMilu;
import ast.*;
import java.util.LinkedList;
import java_cup.runtime.ComplexSymbolFactory.Location;

/** CUP v0.11b beta 20140220 generated parser.
  * @version Mon Apr 06 18:10:09 CEST 2026
  */
public class AnalizadorSintacticoMilu extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public AnalizadorSintacticoMilu() {super();}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintacticoMilu(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintacticoMilu(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\125\000\002\002\003\000\002\002\004\000\002\030" +
    "\005\000\002\030\004\000\002\030\004\000\002\030\004" +
    "\000\002\030\003\000\002\030\003\000\002\026\004\000" +
    "\002\026\003\000\002\003\004\000\002\003\004\000\002" +
    "\003\003\000\002\003\003\000\002\003\003\000\002\003" +
    "\007\000\002\003\007\000\002\003\005\000\002\004\006" +
    "\000\002\004\010\000\002\005\005\000\002\011\015\000" +
    "\002\032\010\000\002\032\006\000\002\032\002\000\002" +
    "\040\003\000\002\040\002\000\002\033\005\000\002\033" +
    "\003\000\002\033\002\000\002\024\003\000\002\024\003" +
    "\000\002\024\003\000\002\024\010\000\002\024\004\000" +
    "\002\024\003\000\002\025\003\000\002\025\003\000\002" +
    "\012\010\000\002\027\005\000\002\027\002\000\002\006" +
    "\011\000\002\007\015\000\002\010\012\000\002\031\006" +
    "\000\002\031\002\000\002\013\005\000\002\013\003\000" +
    "\002\014\005\000\002\014\003\000\002\015\005\000\002" +
    "\015\003\000\002\016\005\000\002\016\003\000\002\017" +
    "\005\000\002\017\003\000\002\020\004\000\002\020\004" +
    "\000\002\020\003\000\002\021\006\000\002\021\005\000" +
    "\002\021\003\000\002\022\003\000\002\022\003\000\002" +
    "\022\005\000\002\022\004\000\002\022\006\000\002\023" +
    "\003\000\002\023\003\000\002\023\003\000\002\023\003" +
    "\000\002\034\003\000\002\034\003\000\002\034\003\000" +
    "\002\034\003\000\002\034\003\000\002\034\003\000\002" +
    "\035\003\000\002\035\003\000\002\036\003\000\002\036" +
    "\003\000\002\036\003\000\002\037\003\000\002\037\003" +
    "\000\002\037\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\253\000\010\046\004\047\006\060\010\001\002\000" +
    "\004\010\251\001\002\000\012\002\ufffb\046\ufffb\047\ufffb" +
    "\060\ufffb\001\002\000\004\010\032\001\002\000\004\002" +
    "\031\001\002\000\004\010\021\001\002\000\012\002\ufffa" +
    "\046\ufffa\047\ufffa\060\ufffa\001\002\000\004\007\020\001" +
    "\002\000\012\002\001\046\004\047\006\060\010\001\002" +
    "\000\012\002\ufffe\046\ufffe\047\ufffe\060\ufffe\001\002\000" +
    "\012\002\ufffd\046\ufffd\047\ufffd\060\ufffd\001\002\000\004" +
    "\007\017\001\002\000\012\002\uffff\046\uffff\047\uffff\060" +
    "\uffff\001\002\000\012\002\ufffc\046\ufffc\047\ufffc\060\ufffc" +
    "\001\002\000\004\006\022\001\002\000\004\037\023\001" +
    "\002\000\006\040\uffd9\046\004\001\002\000\004\007\027" +
    "\001\002\000\004\040\026\001\002\000\012\002\uffdb\046" +
    "\uffdb\047\uffdb\060\uffdb\001\002\000\006\040\uffd9\046\004" +
    "\001\002\000\004\040\uffda\001\002\000\004\002\000\001" +
    "\002\000\004\033\033\001\002\000\010\010\uffe7\022\034" +
    "\034\uffe9\001\002\000\004\010\uffe8\001\002\000\004\010" +
    "\244\001\002\000\004\034\037\001\002\000\004\006\040" +
    "\001\002\000\020\010\050\016\044\042\041\043\042\044" +
    "\051\045\043\056\046\001\002\000\054\004\uffe3\005\uffe3" +
    "\007\uffe3\014\uffe3\015\uffe3\016\uffe3\017\uffe3\020\uffe3\023" +
    "\uffe3\024\uffe3\025\uffe3\026\uffe3\027\uffe3\030\uffe3\031\uffe3" +
    "\032\uffe3\034\uffe3\035\uffe3\036\uffe3\041\uffe3\061\uffe3\001" +
    "\002\000\054\004\uffe1\005\uffe1\007\uffe1\014\uffe1\015\uffe1" +
    "\016\uffe1\017\uffe1\020\uffe1\023\uffe1\024\uffe1\025\uffe1\026" +
    "\uffe1\027\uffe1\030\uffe1\031\uffe1\032\uffe1\034\uffe1\035\uffe1" +
    "\036\uffe1\041\uffe1\061\uffe1\001\002\000\004\035\237\001" +
    "\002\000\016\010\050\016\044\042\041\043\042\044\051" +
    "\045\043\001\002\000\004\004\uffdd\001\002\000\004\004" +
    "\uffdc\001\002\000\004\004\052\001\002\000\054\004\uffde" +
    "\005\uffde\007\uffde\014\uffde\015\uffde\016\uffde\017\uffde\020" +
    "\uffde\023\uffde\024\uffde\025\uffde\026\uffde\027\uffde\030\uffde" +
    "\031\uffde\032\uffde\034\uffde\035\uffde\036\uffde\041\uffde\061" +
    "\uffde\001\002\000\054\004\uffe2\005\uffe2\007\uffe2\014\uffe2" +
    "\015\uffe2\016\uffe2\017\uffe2\020\uffe2\023\uffe2\024\uffe2\025" +
    "\uffe2\026\uffe2\027\uffe2\030\uffe2\031\uffe2\032\uffe2\034\uffe2" +
    "\035\uffe2\036\uffe2\041\uffe2\061\uffe2\001\002\000\004\037" +
    "\053\001\002\000\044\010\100\011\105\012\074\013\062" +
    "\015\107\016\071\021\056\022\064\033\075\046\004\050" +
    "\067\052\057\053\106\054\060\057\101\062\076\063\102" +
    "\001\002\000\046\010\ufff4\011\ufff4\012\ufff4\013\ufff4\015" +
    "\ufff4\016\ufff4\021\ufff4\022\ufff4\033\ufff4\040\ufff4\046\ufff4" +
    "\050\ufff4\052\ufff4\053\ufff4\054\ufff4\057\ufff4\062\ufff4\063" +
    "\ufff4\001\002\000\052\005\uffc3\007\uffc3\014\uffc3\015\uffc3" +
    "\016\uffc3\017\uffc3\020\uffc3\023\uffc3\024\uffc3\025\uffc3\026" +
    "\uffc3\027\uffc3\030\uffc3\031\uffc3\032\uffc3\034\uffc3\035\uffc3" +
    "\036\uffc3\041\uffc3\061\uffc3\001\002\000\030\010\uffaf\011" +
    "\uffaf\012\uffaf\013\uffaf\015\uffaf\016\uffaf\021\uffaf\022\uffaf" +
    "\033\uffaf\057\uffaf\062\uffaf\001\002\000\004\033\230\001" +
    "\002\000\030\010\112\011\105\012\074\013\062\015\107" +
    "\016\071\021\056\022\064\033\075\057\101\062\076\001" +
    "\002\000\052\005\uffc4\007\uffc4\014\uffc4\015\uffc4\016\uffc4" +
    "\017\uffc4\020\uffc4\023\uffc4\024\uffc4\025\uffc4\026\uffc4\027" +
    "\uffc4\030\uffc4\031\uffc4\032\uffc4\034\uffc4\035\uffc4\036\uffc4" +
    "\041\uffc4\061\uffc4\001\002\000\052\005\uffbc\007\uffbc\014" +
    "\uffbc\015\uffbc\016\uffbc\017\uffbc\020\uffbc\023\uffbc\024\uffbc" +
    "\025\uffbc\026\uffbc\027\uffbc\030\uffbc\031\uffbc\032\uffbc\034" +
    "\uffbc\035\uffbc\036\uffbc\041\uffbc\061\uffbc\001\002\000\052" +
    "\005\uffc7\007\uffc7\014\uffc7\015\uffc7\016\uffc7\017\uffc7\020" +
    "\uffc7\023\uffc7\024\uffc7\025\uffc7\026\uffc7\027\uffc7\030\uffc7" +
    "\031\uffc7\032\uffc7\034\uffc7\035\221\036\uffc7\041\uffc7\061" +
    "\222\001\002\000\030\010\uffad\011\uffad\012\uffad\013\uffad" +
    "\015\uffad\016\uffad\021\uffad\022\uffad\033\uffad\057\uffad\062" +
    "\uffad\001\002\000\046\010\100\011\105\012\074\013\062" +
    "\015\107\016\071\021\056\022\064\033\075\040\220\046" +
    "\004\050\067\052\057\053\106\054\060\057\101\062\076" +
    "\063\102\001\002\000\004\041\216\001\002\000\004\033" +
    "\203\001\002\000\004\007\202\001\002\000\030\010\112" +
    "\011\105\012\074\013\062\015\107\016\071\021\056\022" +
    "\064\033\075\057\101\062\076\001\002\000\046\010\ufff8" +
    "\011\ufff8\012\ufff8\013\ufff8\015\ufff8\016\ufff8\021\ufff8\022" +
    "\ufff8\033\ufff8\040\ufff8\046\ufff8\050\ufff8\052\ufff8\053\ufff8" +
    "\054\ufff8\057\ufff8\062\ufff8\063\ufff8\001\002\000\004\007" +
    "\200\001\002\000\052\005\uffbd\007\uffbd\014\uffbd\015\uffbd" +
    "\016\uffbd\017\uffbd\020\uffbd\023\uffbd\024\uffbd\025\uffbd\026" +
    "\uffbd\027\uffbd\030\uffbd\031\uffbd\032\uffbd\034\uffbd\035\uffbd" +
    "\036\uffbd\041\uffbd\061\uffbd\001\002\000\030\010\112\011" +
    "\105\012\074\013\062\015\107\016\071\021\056\022\064" +
    "\033\075\057\101\062\076\001\002\000\052\005\uffbb\007" +
    "\uffbb\014\uffbb\015\uffbb\016\uffbb\017\uffbb\020\uffbb\023\uffbb" +
    "\024\uffbb\025\uffbb\026\uffbb\027\uffbb\030\uffbb\031\uffbb\032" +
    "\uffbb\034\uffbb\035\uffbb\036\uffbb\041\uffbb\061\uffbb\001\002" +
    "\000\046\010\ufff3\011\ufff3\012\ufff3\013\ufff3\015\ufff3\016" +
    "\ufff3\021\ufff3\022\ufff3\033\ufff3\040\ufff3\046\ufff3\050\ufff3" +
    "\052\ufff3\053\ufff3\054\ufff3\057\ufff3\062\ufff3\063\ufff3\001" +
    "\002\000\012\033\172\035\uffc2\041\uffc2\061\uffc2\001\002" +
    "\000\016\010\050\016\044\042\041\043\042\044\051\045" +
    "\043\001\002\000\004\033\165\001\002\000\046\010\ufff5" +
    "\011\ufff5\012\ufff5\013\ufff5\015\ufff5\016\ufff5\021\ufff5\022" +
    "\ufff5\033\ufff5\040\ufff5\046\ufff5\050\ufff5\052\ufff5\053\ufff5" +
    "\054\ufff5\057\ufff5\062\ufff5\063\ufff5\001\002\000\030\010" +
    "\112\011\105\012\074\013\062\015\107\016\071\021\056" +
    "\022\064\033\075\057\101\062\076\001\002\000\052\005" +
    "\uffbe\007\uffbe\014\uffbe\015\uffbe\016\uffbe\017\uffbe\020\uffbe" +
    "\023\uffbe\024\uffbe\025\uffbe\026\uffbe\027\uffbe\030\uffbe\031" +
    "\uffbe\032\uffbe\034\uffbe\035\uffbe\036\uffbe\041\uffbe\061\uffbe" +
    "\001\002\000\004\033\110\001\002\000\030\010\uffae\011" +
    "\uffae\012\uffae\013\uffae\015\uffae\016\uffae\021\uffae\022\uffae" +
    "\033\uffae\057\uffae\062\uffae\001\002\000\030\010\112\011" +
    "\105\012\074\013\062\015\107\016\071\021\056\022\064" +
    "\033\075\057\101\062\076\001\002\000\004\007\153\001" +
    "\002\000\054\005\uffc2\007\uffc2\014\uffc2\015\uffc2\016\uffc2" +
    "\017\uffc2\020\uffc2\023\uffc2\024\uffc2\025\uffc2\026\uffc2\027" +
    "\uffc2\030\uffc2\031\uffc2\032\uffc2\033\113\034\uffc2\035\uffc2" +
    "\036\uffc2\041\uffc2\061\uffc2\001\002\000\032\010\112\011" +
    "\105\012\074\013\062\015\107\016\071\021\056\022\064" +
    "\033\075\034\uffe4\057\101\062\076\001\002\000\044\005" +
    "\uffca\007\uffca\014\uffca\015\uffca\016\uffca\017\uffca\020\uffca" +
    "\023\uffca\024\uffca\025\uffca\026\uffca\027\uffca\030\uffca\031" +
    "\uffca\032\uffca\034\uffca\036\uffca\001\002\000\044\005\uffcc" +
    "\007\uffcc\014\uffcc\015\uffcc\016\150\017\151\020\146\023" +
    "\uffcc\024\uffcc\025\uffcc\026\uffcc\027\uffcc\030\uffcc\031\uffcc" +
    "\032\uffcc\034\uffcc\036\uffcc\001\002\000\036\005\uffce\007" +
    "\uffce\014\134\015\143\023\141\024\142\025\133\026\140" +
    "\027\132\030\137\031\uffce\032\uffce\034\uffce\036\uffce\001" +
    "\002\000\016\005\uffd0\007\uffd0\031\uffd0\032\uffd0\034\uffd0" +
    "\036\uffd0\001\002\000\016\005\uffd2\007\uffd2\031\126\032" +
    "\127\034\uffd2\036\uffd2\001\002\000\006\005\124\034\uffe5" +
    "\001\002\000\004\034\123\001\002\000\052\005\uffbf\007" +
    "\uffbf\014\uffbf\015\uffbf\016\uffbf\017\uffbf\020\uffbf\023\uffbf" +
    "\024\uffbf\025\uffbf\026\uffbf\027\uffbf\030\uffbf\031\uffbf\032" +
    "\uffbf\034\uffbf\035\uffbf\036\uffbf\041\uffbf\061\uffbf\001\002" +
    "\000\032\010\112\011\105\012\074\013\062\015\107\016" +
    "\071\021\056\022\064\033\075\034\uffe4\057\101\062\076" +
    "\001\002\000\004\034\uffe6\001\002\000\030\010\112\011" +
    "\105\012\074\013\062\015\107\016\071\021\056\022\064" +
    "\033\075\057\101\062\076\001\002\000\030\010\112\011" +
    "\105\012\074\013\062\015\107\016\071\021\056\022\064" +
    "\033\075\057\101\062\076\001\002\000\012\005\uffd3\007" +
    "\uffd3\034\uffd3\036\uffd3\001\002\000\016\005\uffd1\007\uffd1" +
    "\031\uffd1\032\uffd1\034\uffd1\036\uffd1\001\002\000\030\010" +
    "\uffb6\011\uffb6\012\uffb6\013\uffb6\015\uffb6\016\uffb6\021\uffb6" +
    "\022\uffb6\033\uffb6\057\uffb6\062\uffb6\001\002\000\030\010" +
    "\uffb8\011\uffb8\012\uffb8\013\uffb8\015\uffb8\016\uffb8\021\uffb8" +
    "\022\uffb8\033\uffb8\057\uffb8\062\uffb8\001\002\000\030\010" +
    "\uffb4\011\uffb4\012\uffb4\013\uffb4\015\uffb4\016\uffb4\021\uffb4" +
    "\022\uffb4\033\uffb4\057\uffb4\062\uffb4\001\002\000\030\010" +
    "\112\011\105\012\074\013\062\015\107\016\071\021\056" +
    "\022\064\033\075\057\101\062\076\001\002\000\030\010" +
    "\112\011\105\012\074\013\062\015\107\016\071\021\056" +
    "\022\064\033\075\057\101\062\076\001\002\000\030\010" +
    "\uffb5\011\uffb5\012\uffb5\013\uffb5\015\uffb5\016\uffb5\021\uffb5" +
    "\022\uffb5\033\uffb5\057\uffb5\062\uffb5\001\002\000\030\010" +
    "\uffb7\011\uffb7\012\uffb7\013\uffb7\015\uffb7\016\uffb7\021\uffb7" +
    "\022\uffb7\033\uffb7\057\uffb7\062\uffb7\001\002\000\030\010" +
    "\uffba\011\uffba\012\uffba\013\uffba\015\uffba\016\uffba\021\uffba" +
    "\022\uffba\033\uffba\057\uffba\062\uffba\001\002\000\030\010" +
    "\uffb9\011\uffb9\012\uffb9\013\uffb9\015\uffb9\016\uffb9\021\uffb9" +
    "\022\uffb9\033\uffb9\057\uffb9\062\uffb9\001\002\000\030\010" +
    "\uffb3\011\uffb3\012\uffb3\013\uffb3\015\uffb3\016\uffb3\021\uffb3" +
    "\022\uffb3\033\uffb3\057\uffb3\062\uffb3\001\002\000\022\005" +
    "\uffcf\007\uffcf\014\134\015\143\031\uffcf\032\uffcf\034\uffcf" +
    "\036\uffcf\001\002\000\044\005\uffcd\007\uffcd\014\uffcd\015" +
    "\uffcd\016\150\017\151\020\146\023\uffcd\024\uffcd\025\uffcd" +
    "\026\uffcd\027\uffcd\030\uffcd\031\uffcd\032\uffcd\034\uffcd\036" +
    "\uffcd\001\002\000\030\010\uffb0\011\uffb0\012\uffb0\013\uffb0" +
    "\015\uffb0\016\uffb0\021\uffb0\022\uffb0\033\uffb0\057\uffb0\062" +
    "\uffb0\001\002\000\030\010\112\011\105\012\074\013\062" +
    "\015\107\016\071\021\056\022\064\033\075\057\101\062" +
    "\076\001\002\000\030\010\uffb2\011\uffb2\012\uffb2\013\uffb2" +
    "\015\uffb2\016\uffb2\021\uffb2\022\uffb2\033\uffb2\057\uffb2\062" +
    "\uffb2\001\002\000\030\010\uffb1\011\uffb1\012\uffb1\013\uffb1" +
    "\015\uffb1\016\uffb1\021\uffb1\022\uffb1\033\uffb1\057\uffb1\062" +
    "\uffb1\001\002\000\044\005\uffcb\007\uffcb\014\uffcb\015\uffcb" +
    "\016\uffcb\017\uffcb\020\uffcb\023\uffcb\024\uffcb\025\uffcb\026" +
    "\uffcb\027\uffcb\030\uffcb\031\uffcb\032\uffcb\034\uffcb\036\uffcb" +
    "\001\002\000\030\010\112\011\105\012\074\013\062\015" +
    "\107\016\071\021\056\022\064\033\075\057\101\062\076" +
    "\001\002\000\004\007\155\001\002\000\030\010\112\011" +
    "\105\012\074\013\062\015\107\016\071\021\056\022\064" +
    "\033\075\057\101\062\076\001\002\000\004\034\157\001" +
    "\002\000\004\037\160\001\002\000\044\010\100\011\105" +
    "\012\074\013\062\015\107\016\071\021\056\022\064\033" +
    "\075\046\004\050\067\052\057\053\106\054\060\057\101" +
    "\062\076\063\102\001\002\000\046\010\100\011\105\012" +
    "\074\013\062\015\107\016\071\021\056\022\064\033\075" +
    "\040\162\046\004\050\067\052\057\053\106\054\060\057" +
    "\101\062\076\063\102\001\002\000\046\010\uffd7\011\uffd7" +
    "\012\uffd7\013\uffd7\015\uffd7\016\uffd7\021\uffd7\022\uffd7\033" +
    "\uffd7\040\uffd7\046\uffd7\050\uffd7\052\uffd7\053\uffd7\054\uffd7" +
    "\057\uffd7\062\uffd7\063\uffd7\001\002\000\046\010\ufff9\011" +
    "\ufff9\012\ufff9\013\ufff9\015\ufff9\016\ufff9\021\ufff9\022\ufff9" +
    "\033\ufff9\040\ufff9\046\ufff9\050\ufff9\052\ufff9\053\ufff9\054" +
    "\ufff9\057\ufff9\062\ufff9\063\ufff9\001\002\000\046\005\uffc9" +
    "\007\uffc9\014\uffc9\015\uffc9\016\uffc9\017\uffc9\020\uffc9\023" +
    "\uffc9\024\uffc9\025\uffc9\026\uffc9\027\uffc9\030\uffc9\031\uffc9" +
    "\032\uffc9\034\uffc9\036\uffc9\041\uffc9\001\002\000\030\010" +
    "\112\011\105\012\074\013\062\015\107\016\071\021\056" +
    "\022\064\033\075\057\101\062\076\001\002\000\004\034" +
    "\167\001\002\000\004\007\170\001\002\000\046\010\ufff2" +
    "\011\ufff2\012\ufff2\013\ufff2\015\ufff2\016\ufff2\021\ufff2\022" +
    "\ufff2\033\ufff2\040\ufff2\046\ufff2\050\ufff2\052\ufff2\053\ufff2" +
    "\054\ufff2\057\ufff2\062\ufff2\063\ufff2\001\002\000\052\005" +
    "\uffc0\007\uffc0\014\uffc0\015\uffc0\016\uffc0\017\uffc0\020\uffc0" +
    "\023\uffc0\024\uffc0\025\uffc0\026\uffc0\027\uffc0\030\uffc0\031" +
    "\uffc0\032\uffc0\034\uffc0\035\uffc0\036\uffc0\041\uffc0\061\uffc0" +
    "\001\002\000\032\010\112\011\105\012\074\013\062\015" +
    "\107\016\071\021\056\022\064\033\075\034\uffe4\057\101" +
    "\062\076\001\002\000\004\034\174\001\002\000\012\007" +
    "\175\035\uffbf\041\uffbf\061\uffbf\001\002\000\046\010\ufff1" +
    "\011\ufff1\012\ufff1\013\ufff1\015\ufff1\016\ufff1\021\ufff1\022" +
    "\ufff1\033\ufff1\040\ufff1\046\ufff1\050\ufff1\052\ufff1\053\ufff1" +
    "\054\ufff1\057\ufff1\062\ufff1\063\ufff1\001\002\000\004\034" +
    "\177\001\002\000\052\005\uffc1\007\uffc1\014\uffc1\015\uffc1" +
    "\016\uffc1\017\uffc1\020\uffc1\023\uffc1\024\uffc1\025\uffc1\026" +
    "\uffc1\027\uffc1\030\uffc1\031\uffc1\032\uffc1\034\uffc1\035\uffc1" +
    "\036\uffc1\041\uffc1\061\uffc1\001\002\000\046\010\ufff6\011" +
    "\ufff6\012\ufff6\013\ufff6\015\ufff6\016\ufff6\021\ufff6\022\ufff6" +
    "\033\ufff6\040\ufff6\046\ufff6\050\ufff6\052\ufff6\053\ufff6\054" +
    "\ufff6\057\ufff6\062\ufff6\063\ufff6\001\002\000\046\005\uffc8" +
    "\007\uffc8\014\uffc8\015\uffc8\016\uffc8\017\uffc8\020\uffc8\023" +
    "\uffc8\024\uffc8\025\uffc8\026\uffc8\027\uffc8\030\uffc8\031\uffc8" +
    "\032\uffc8\034\uffc8\036\uffc8\041\uffc8\001\002\000\046\010" +
    "\ufff7\011\ufff7\012\ufff7\013\ufff7\015\ufff7\016\ufff7\021\ufff7" +
    "\022\ufff7\033\ufff7\040\ufff7\046\ufff7\050\ufff7\052\ufff7\053" +
    "\ufff7\054\ufff7\057\ufff7\062\ufff7\063\ufff7\001\002\000\030" +
    "\010\112\011\105\012\074\013\062\015\107\016\071\021" +
    "\056\022\064\033\075\057\101\062\076\001\002\000\004" +
    "\034\205\001\002\000\004\037\206\001\002\000\044\010" +
    "\100\011\105\012\074\013\062\015\107\016\071\021\056" +
    "\022\064\033\075\046\004\050\067\052\057\053\106\054" +
    "\060\057\101\062\076\063\102\001\002\000\046\010\100" +
    "\011\105\012\074\013\062\015\107\016\071\021\056\022" +
    "\064\033\075\040\210\046\004\050\067\052\057\053\106" +
    "\054\060\057\101\062\076\063\102\001\002\000\050\010" +
    "\uffd4\011\uffd4\012\uffd4\013\uffd4\015\uffd4\016\uffd4\021\uffd4" +
    "\022\uffd4\033\uffd4\040\uffd4\046\uffd4\050\uffd4\051\211\052" +
    "\uffd4\053\uffd4\054\uffd4\057\uffd4\062\uffd4\063\uffd4\001\002" +
    "\000\004\037\213\001\002\000\046\010\uffd6\011\uffd6\012" +
    "\uffd6\013\uffd6\015\uffd6\016\uffd6\021\uffd6\022\uffd6\033\uffd6" +
    "\040\uffd6\046\uffd6\050\uffd6\052\uffd6\053\uffd6\054\uffd6\057" +
    "\uffd6\062\uffd6\063\uffd6\001\002\000\044\010\100\011\105" +
    "\012\074\013\062\015\107\016\071\021\056\022\064\033" +
    "\075\046\004\050\067\052\057\053\106\054\060\057\101" +
    "\062\076\063\102\001\002\000\046\010\100\011\105\012" +
    "\074\013\062\015\107\016\071\021\056\022\064\033\075" +
    "\040\215\046\004\050\067\052\057\053\106\054\060\057" +
    "\101\062\076\063\102\001\002\000\046\010\uffd5\011\uffd5" +
    "\012\uffd5\013\uffd5\015\uffd5\016\uffd5\021\uffd5\022\uffd5\033" +
    "\uffd5\040\uffd5\046\uffd5\050\uffd5\052\uffd5\053\uffd5\054\uffd5" +
    "\057\uffd5\062\uffd5\063\uffd5\001\002\000\030\010\112\011" +
    "\105\012\074\013\062\015\107\016\071\021\056\022\064" +
    "\033\075\057\101\062\076\001\002\000\006\007\uffed\034" +
    "\uffed\001\002\000\012\002\uffec\046\uffec\047\uffec\060\uffec" +
    "\001\002\000\030\010\112\011\105\012\074\013\062\015" +
    "\107\016\071\021\056\022\064\033\075\057\101\062\076" +
    "\001\002\000\004\010\223\001\002\000\052\005\uffc5\007" +
    "\uffc5\014\uffc5\015\uffc5\016\uffc5\017\uffc5\020\uffc5\023\uffc5" +
    "\024\uffc5\025\uffc5\026\uffc5\027\uffc5\030\uffc5\031\uffc5\032" +
    "\uffc5\034\uffc5\035\uffc5\036\uffc5\041\uffc5\061\uffc5\001\002" +
    "\000\004\036\225\001\002\000\052\005\uffc6\007\uffc6\014" +
    "\uffc6\015\uffc6\016\uffc6\017\uffc6\020\uffc6\023\uffc6\024\uffc6" +
    "\025\uffc6\026\uffc6\027\uffc6\030\uffc6\031\uffc6\032\uffc6\034" +
    "\uffc6\035\uffc6\036\uffc6\041\uffc6\061\uffc6\001\002\000\004" +
    "\007\227\001\002\000\046\010\ufff0\011\ufff0\012\ufff0\013" +
    "\ufff0\015\ufff0\016\ufff0\021\ufff0\022\ufff0\033\ufff0\040\ufff0" +
    "\046\ufff0\050\ufff0\052\ufff0\053\ufff0\054\ufff0\057\ufff0\062" +
    "\ufff0\063\ufff0\001\002\000\030\010\112\011\105\012\074" +
    "\013\062\015\107\016\071\021\056\022\064\033\075\057" +
    "\101\062\076\001\002\000\004\034\232\001\002\000\004" +
    "\037\233\001\002\000\044\010\100\011\105\012\074\013" +
    "\062\015\107\016\071\021\056\022\064\033\075\046\004" +
    "\050\067\052\057\053\106\054\060\057\101\062\076\063" +
    "\102\001\002\000\046\010\100\011\105\012\074\013\062" +
    "\015\107\016\071\021\056\022\064\033\075\040\235\046" +
    "\004\050\067\052\057\053\106\054\060\057\101\062\076" +
    "\063\102\001\002\000\046\010\uffd8\011\uffd8\012\uffd8\013" +
    "\uffd8\015\uffd8\016\uffd8\021\uffd8\022\uffd8\033\uffd8\040\uffd8" +
    "\046\uffd8\050\uffd8\052\uffd8\053\uffd8\054\uffd8\057\uffd8\062" +
    "\uffd8\063\uffd8\001\002\000\054\004\uffdf\005\uffdf\007\uffdf" +
    "\014\uffdf\015\uffdf\016\uffdf\017\uffdf\020\uffdf\023\uffdf\024" +
    "\uffdf\025\uffdf\026\uffdf\027\uffdf\030\uffdf\031\uffdf\032\uffdf" +
    "\034\uffdf\035\uffdf\036\uffdf\041\uffdf\061\uffdf\001\002\000" +
    "\030\010\112\011\105\012\074\013\062\015\107\016\071" +
    "\021\056\022\064\033\075\057\101\062\076\001\002\000" +
    "\004\036\241\001\002\000\004\055\242\001\002\000\016" +
    "\010\050\016\044\042\041\043\042\044\051\045\043\001" +
    "\002\000\054\004\uffe0\005\uffe0\007\uffe0\014\uffe0\015\uffe0" +
    "\016\uffe0\017\uffe0\020\uffe0\023\uffe0\024\uffe0\025\uffe0\026" +
    "\uffe0\027\uffe0\030\uffe0\031\uffe0\032\uffe0\034\uffe0\035\uffe0" +
    "\036\uffe0\041\uffe0\061\uffe0\001\002\000\004\006\245\001" +
    "\002\000\016\010\050\016\044\042\041\043\042\044\051" +
    "\045\043\001\002\000\006\005\247\034\uffea\001\002\000" +
    "\010\010\uffe7\022\034\034\uffe9\001\002\000\004\034\uffeb" +
    "\001\002\000\004\006\252\001\002\000\016\010\050\016" +
    "\044\042\041\043\042\044\051\045\043\001\002\000\006" +
    "\007\uffef\041\254\001\002\000\030\010\112\011\105\012" +
    "\074\013\062\015\107\016\071\021\056\022\064\033\075" +
    "\057\101\062\076\001\002\000\004\007\uffee\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\253\000\014\002\006\004\011\011\004\012\010\030" +
    "\012\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\004\015\011\013\012\014" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\004\023\027\024\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\004\023\027\027\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\032\035\040\034\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\024\044\025\046\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\024" +
    "\235\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\032\003\071\004\067\005\072\006\102\007\053" +
    "\010\076\020\065\021\062\022\060\023\054\026\064\037" +
    "\103\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\026\013\225\014\117\015" +
    "\116\016\115\017\114\020\113\021\062\022\060\023\054" +
    "\037\103\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\030\003\162\004\067" +
    "\005\072\006\102\007\053\010\076\020\065\021\062\022" +
    "\060\023\054\037\103\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\014\020\200\021\062\022" +
    "\060\023\054\037\103\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\026\013\175\014\117\015" +
    "\116\016\115\017\114\020\113\021\062\022\060\023\054" +
    "\037\103\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\024\170\001\001\000\002\001\001" +
    "\000\002\001\001\000\014\020\163\021\062\022\060\023" +
    "\054\037\103\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\016\005\110\020\065\021\062\022" +
    "\060\023\054\037\103\001\001\000\002\001\001\000\002" +
    "\001\001\000\030\013\120\014\117\015\116\016\115\017" +
    "\114\020\113\021\062\022\060\023\054\033\121\037\103" +
    "\001\001\000\002\001\001\000\004\036\146\001\001\000" +
    "\006\034\135\035\134\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\030\013\120\014\117\015\116\016\115\017\114" +
    "\020\113\021\062\022\060\023\054\033\124\037\103\001" +
    "\001\000\002\001\001\000\022\015\130\016\115\017\114" +
    "\020\113\021\062\022\060\023\054\037\103\001\001\000" +
    "\026\013\127\014\117\015\116\016\115\017\114\020\113" +
    "\021\062\022\060\023\054\037\103\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\016\017\144\020\113\021\062\022" +
    "\060\023\054\037\103\001\001\000\020\016\143\017\114" +
    "\020\113\021\062\022\060\023\054\037\103\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\035\134\001\001\000" +
    "\004\036\146\001\001\000\002\001\001\000\014\020\151" +
    "\021\062\022\060\023\054\037\103\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\026\013\153" +
    "\014\117\015\116\016\115\017\114\020\113\021\062\022" +
    "\060\023\054\037\103\001\001\000\002\001\001\000\016" +
    "\005\155\020\065\021\062\022\060\023\054\037\103\001" +
    "\001\000\002\001\001\000\002\001\001\000\032\003\071" +
    "\004\067\005\072\006\102\007\053\010\076\020\065\021" +
    "\062\022\060\023\054\026\160\037\103\001\001\000\030" +
    "\003\162\004\067\005\072\006\102\007\053\010\076\020" +
    "\065\021\062\022\060\023\054\037\103\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\026\013" +
    "\165\014\117\015\116\016\115\017\114\020\113\021\062" +
    "\022\060\023\054\037\103\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\030" +
    "\013\120\014\117\015\116\016\115\017\114\020\113\021" +
    "\062\022\060\023\054\033\172\037\103\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\026\013\203\014\117\015\116\016" +
    "\115\017\114\020\113\021\062\022\060\023\054\037\103" +
    "\001\001\000\002\001\001\000\002\001\001\000\032\003" +
    "\071\004\067\005\072\006\102\007\053\010\076\020\065" +
    "\021\062\022\060\023\054\026\206\037\103\001\001\000" +
    "\030\003\162\004\067\005\072\006\102\007\053\010\076" +
    "\020\065\021\062\022\060\023\054\037\103\001\001\000" +
    "\004\031\211\001\001\000\002\001\001\000\002\001\001" +
    "\000\032\003\071\004\067\005\072\006\102\007\053\010" +
    "\076\020\065\021\062\022\060\023\054\026\213\037\103" +
    "\001\001\000\030\003\162\004\067\005\072\006\102\007" +
    "\053\010\076\020\065\021\062\022\060\023\054\037\103" +
    "\001\001\000\002\001\001\000\026\013\216\014\117\015" +
    "\116\016\115\017\114\020\113\021\062\022\060\023\054" +
    "\037\103\001\001\000\002\001\001\000\002\001\001\000" +
    "\026\013\223\014\117\015\116\016\115\017\114\020\113" +
    "\021\062\022\060\023\054\037\103\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\026\013\230\014" +
    "\117\015\116\016\115\017\114\020\113\021\062\022\060" +
    "\023\054\037\103\001\001\000\002\001\001\000\002\001" +
    "\001\000\032\003\071\004\067\005\072\006\102\007\053" +
    "\010\076\020\065\021\062\022\060\023\054\026\233\037" +
    "\103\001\001\000\030\003\162\004\067\005\072\006\102" +
    "\007\053\010\076\020\065\021\062\022\060\023\054\037" +
    "\103\001\001\000\002\001\001\000\002\001\001\000\022" +
    "\015\237\016\115\017\114\020\113\021\062\022\060\023" +
    "\054\037\103\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\024\242\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\024\245\001\001\000\002\001\001\000\006" +
    "\032\247\040\034\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\024\252\001\001\000\002\001\001\000\026" +
    "\013\254\014\117\015\116\016\115\017\114\020\113\021" +
    "\062\022\060\023\054\037\103\001\001\000\002\001\001" +
    "" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$AnalizadorSintacticoMilu$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$AnalizadorSintacticoMilu$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$AnalizadorSintacticoMilu$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {
 
   errores = new GestionErroresMilu();
   AnalizadorLexicoMilu alex = (AnalizadorLexicoMilu)getScanner();
   alex.fijaGestionErrores(errores);

    }

  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 return getScanner().next_token(); 
    }

 
   private GestionErroresMilu errores;
   public void syntax_error(Symbol unidadLexica) {
     errores.errorSintactico((UnidadLexica)unidadLexica);
   }
   public int fila(int index) {
     return ((java_cup.runtime.Symbol)stack.peek()).left;
   }
  public int columna(int index) {
     return ((java_cup.runtime.Symbol)stack.peek()).right;
   }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$AnalizadorSintacticoMilu$actions {
  private final AnalizadorSintacticoMilu parser;

  /** Constructor */
  CUP$AnalizadorSintacticoMilu$actions(AnalizadorSintacticoMilu parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$AnalizadorSintacticoMilu$do_action_part00000000(
    int                        CUP$AnalizadorSintacticoMilu$act_num,
    java_cup.runtime.lr_parser CUP$AnalizadorSintacticoMilu$parser,
    java.util.Stack            CUP$AnalizadorSintacticoMilu$stack,
    int                        CUP$AnalizadorSintacticoMilu$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$AnalizadorSintacticoMilu$result;

      /* select the action based on the action number */
      switch (CUP$AnalizadorSintacticoMilu$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // S ::= Ds 
            {
              Nodo RESULT =null;
		LinkedList<Nodo> lista = (LinkedList<Nodo>)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = new Programa(lista, parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("S",0, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= S EOF 
            {
              Object RESULT =null;
		Nodo start_val = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-1)).value;
		RESULT = start_val;
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("$START",0, RESULT);
            }
          /* ACCEPT */
          CUP$AnalizadorSintacticoMilu$parser.done_parsing();
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Ds ::= Ds D SCOLON 
            {
              LinkedList<Nodo> RESULT =null;
		LinkedList<Nodo> lista = (LinkedList<Nodo>)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-2)).value;
		Nodo d = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-1)).value;
		 lista.add(d); RESULT = lista; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("Ds",22, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // Ds ::= Ds FUNDEC 
            {
              LinkedList<Nodo> RESULT =null;
		LinkedList<Nodo> lista = (LinkedList<Nodo>)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-1)).value;
		Nodo f = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 lista.add(f); RESULT = lista; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("Ds",22, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Ds ::= Ds STRUCTDEC 
            {
              LinkedList<Nodo> RESULT =null;
		LinkedList<Nodo> lista = (LinkedList<Nodo>)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-1)).value;
		Nodo st = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 lista.add(st); RESULT = lista; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("Ds",22, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Ds ::= D SCOLON 
            {
              LinkedList<Nodo> RESULT =null;
		Nodo d = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-1)).value;
		 LinkedList<Nodo> l = new LinkedList<>(); l.add(d); RESULT = l; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("Ds",22, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Ds ::= FUNDEC 
            {
              LinkedList<Nodo> RESULT =null;
		Nodo f = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 LinkedList<Nodo> l = new LinkedList<>(); l.add(f); RESULT = l; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("Ds",22, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Ds ::= STRUCTDEC 
            {
              LinkedList<Nodo> RESULT =null;
		Nodo st = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 LinkedList<Nodo> l = new LinkedList<>(); l.add(st); RESULT = l; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("Ds",22, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // BLOQUE ::= BLOQUE B 
            {
              LinkedList<Nodo> RESULT =null;
		LinkedList<Nodo> lista = (LinkedList<Nodo>)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-1)).value;
		Nodo i = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 lista.add(i); RESULT = lista; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("BLOQUE",20, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // BLOQUE ::= B 
            {
              LinkedList<Nodo> RESULT =null;
		Nodo i = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 LinkedList<Nodo> l = new LinkedList<>(); l.add(i); RESULT = l; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("BLOQUE",20, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // B ::= D SCOLON 
            {
              Nodo RESULT =null;
		Nodo d = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-1)).value;
		 RESULT = d; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("B",1, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // B ::= A SCOLON 
            {
              Nodo RESULT =null;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-1)).value;
		 RESULT = a; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("B",1, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // B ::= WHILE_L 
            {
              Nodo RESULT =null;
		Nodo w = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = w; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("B",1, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // B ::= FOR_L 
            {
              Nodo RESULT =null;
		Nodo f = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = f; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("B",1, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // B ::= IFCOND 
            {
              Nodo RESULT =null;
		Nodo i = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = i; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("B",1, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // B ::= FREE PAP E0 PCIERRE SCOLON 
            {
              Nodo RESULT =null;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-2)).value;
		 RESULT = new InstFree((Expresion)e,parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("B",1, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // B ::= IDENTIFICADOR PAP P_LLAMADA PCIERRE SCOLON 
            {
              Nodo RESULT =null;
		String id = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-4)).value;
		LinkedList<Nodo> args = (LinkedList<Nodo>)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-2)).value;
		 RESULT = new InstLlamadaFuncion(id, args, parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("B",1, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // B ::= RETURN E0 SCOLON 
            {
              Nodo RESULT =null;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-1)).value;
		 RESULT = new InstReturn(e, parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("B",1, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // D ::= VAR IDENTIFICADOR COLON T 
            {
              Nodo RESULT =null;
		String id = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-2)).value;
		Tipo t = (Tipo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = new DeclaracionVariable(id, t, null, parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("D",2, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // D ::= VAR IDENTIFICADOR COLON T ASIG E0 
            {
              Nodo RESULT =null;
		String id = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-4)).value;
		Tipo t = (Tipo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-2)).value;
		Nodo exp = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = new DeclaracionVariable(id, t, exp, parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("D",2, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // A ::= E5 ASIG E0 
            {
              Nodo RESULT =null;
		Nodo d = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-2)).value;
		Nodo exp = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = new InstAsignacion((Designador)d, exp, parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("A",3, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // FUNDEC ::= DEF IDENTIFICADOR PAP P PCIERRE COLON T_FUNCT AS BAP BLOQUE BCIERRE 
            {
              Nodo RESULT =null;
		String id = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-9)).value;
		LinkedList<Parametro> params = (LinkedList<Parametro>)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-7)).value;
		Tipo ret = (Tipo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-4)).value;
		LinkedList<Nodo> bloque = (LinkedList<Nodo>)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-1)).value;
		  RESULT = new DeclaracionFuncion(id, params, ret, bloque, parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("FUNDEC",7, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // P ::= PASO IDENTIFICADOR COLON T COMMA P 
            {
              LinkedList<Parametro> RESULT =null;
		String p = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-5)).value;
		String id = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-4)).value;
		Tipo t = (Tipo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-2)).value;
		LinkedList<Parametro> lista = (LinkedList<Parametro>)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 lista.addFirst(new Parametro(id, t, p != null, parser.fila(0), parser.columna(0))); RESULT = lista; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("P",24, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // P ::= PASO IDENTIFICADOR COLON T 
            {
              LinkedList<Parametro> RESULT =null;
		String p = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-3)).value;
		String id = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-2)).value;
		Tipo t = (Tipo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 LinkedList<Parametro> l = new LinkedList<>(); l.add(new Parametro(id, t, p != null, parser.fila(0), parser.columna(0))); RESULT = l; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("P",24, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // P ::= 
            {
              LinkedList<Parametro> RESULT =null;
		 RESULT = new LinkedList<Parametro>(); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("P",24, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // PASO ::= REF 
            {
              String RESULT =null;
		 RESULT = "&"; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("PASO",30, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // PASO ::= 
            {
              String RESULT =null;
		 RESULT = null; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("PASO",30, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // P_LLAMADA ::= E0 COMMA P_LLAMADA 
            {
              LinkedList<Nodo> RESULT =null;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-2)).value;
		LinkedList<Nodo> lista = (LinkedList<Nodo>)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 lista.addFirst(e); RESULT = lista; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("P_LLAMADA",25, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // P_LLAMADA ::= E0 
            {
              LinkedList<Nodo> RESULT =null;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 LinkedList<Nodo> l = new LinkedList<>(); l.add(e); RESULT = l; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("P_LLAMADA",25, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // P_LLAMADA ::= 
            {
              LinkedList<Nodo> RESULT =null;
		 RESULT = new LinkedList<Nodo>(); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("P_LLAMADA",25, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // T ::= INT 
            {
              Tipo RESULT =null;
		String i = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = new TipoInt(parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("T",18, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // T ::= FLOAT 
            {
              Tipo RESULT =null;
		String f = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = new TipoFloat(parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("T",18, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // T ::= BOOL 
            {
              Tipo RESULT =null;
		String b = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = new TipoBool(parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("T",18, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // T ::= ARRAY CAP E2 CCIERRE DE T 
            {
              Tipo RESULT =null;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-3)).value;
		Tipo t = (Tipo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = new TipoArray(e, t, parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("T",18, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // T ::= MULT T 
            {
              Tipo RESULT =null;
		Tipo t = (Tipo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = new TipoPuntero(t, parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("T",18, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // T ::= IDENTIFICADOR 
            {
              Tipo RESULT =null;
		String id = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = new TipoStruct(id, parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("T",18, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // T_FUNCT ::= T 
            {
              Tipo RESULT =null;
		Tipo t = (Tipo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = t; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("T_FUNCT",19, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // T_FUNCT ::= VOID 
            {
              Tipo RESULT =null;
		String v = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = new TipoVoid(parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("T_FUNCT",19, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // STRUCTDEC ::= STRUCT IDENTIFICADOR COLON BAP DECS BCIERRE 
            {
              Nodo RESULT =null;
		String id = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-4)).value;
		LinkedList<Nodo> lista = (LinkedList<Nodo>)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-1)).value;
		  RESULT = new DeclaracionStruct(id, lista, parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("STRUCTDEC",8, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // DECS ::= D SCOLON DECS 
            {
              LinkedList<Nodo> RESULT =null;
		Nodo dec = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-2)).value;
		LinkedList<Nodo> lista = (LinkedList<Nodo>)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 lista.addFirst(dec); RESULT = lista; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("DECS",21, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // DECS ::= 
            {
              LinkedList<Nodo> RESULT =null;
		 RESULT = new LinkedList<Nodo>(); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("DECS",21, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // WHILE_L ::= WHILE PAP E0 PCIERRE BAP BLOQUE BCIERRE 
            {
              Nodo RESULT =null;
		String w = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-6)).value;
		Nodo cond = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-4)).value;
		LinkedList<Nodo> bloque = (LinkedList<Nodo>)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-1)).value;
		  RESULT = new InstWhile(cond, bloque, parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("WHILE_L",4, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // FOR_L ::= FOR PAP A SCOLON E0 SCOLON A PCIERRE BAP BLOQUE BCIERRE 
            {
              Nodo RESULT =null;
		String f = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-10)).value;
		Nodo ini = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-8)).value;
		Nodo cond = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-6)).value;
		Nodo iter = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-4)).value;
		LinkedList<Nodo> bloque = (LinkedList<Nodo>)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-1)).value;
		  RESULT = new InstFor(ini, cond, iter, bloque, parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("FOR_L",5, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // IFCOND ::= IF PAP E0 PCIERRE BAP BLOQUE BCIERRE ELSECOND 
            {
              Nodo RESULT =null;
		Nodo cond = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-5)).value;
		LinkedList<Nodo> si = (LinkedList<Nodo>)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-2)).value;
		LinkedList<Nodo> sino = (LinkedList<Nodo>)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		        RESULT = new InstIf(cond, si, sino, parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("IFCOND",6, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // ELSECOND ::= ELSE BAP BLOQUE BCIERRE 
            {
              LinkedList<Nodo> RESULT =null;
		LinkedList<Nodo> lista = (LinkedList<Nodo>)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-1)).value;
		 RESULT = lista; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("ELSECOND",23, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // ELSECOND ::= 
            {
              LinkedList<Nodo> RESULT =null;
		 RESULT = null; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("ELSECOND",23, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // E0 ::= E1 OR E0 
            {
              Nodo RESULT =null;
		Nodo i = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-2)).value;
		Nodo d = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = new ExpBinaria(i, d, "||", parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("E0",9, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // E0 ::= E1 
            {
              Nodo RESULT =null;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = e; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("E0",9, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // E1 ::= E1 AND E2 
            {
              Nodo RESULT =null;
		Nodo i = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-2)).value;
		Nodo d = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = new ExpBinaria(i, d, "&&", parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("E1",10, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // E1 ::= E2 
            {
              Nodo RESULT =null;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = e; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("E1",10, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // E2 ::= E3 OP0 E3 
            {
              Nodo RESULT =null;
		Nodo i = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-2)).value;
		String op = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-1)).value;
		Nodo d = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = new ExpBinaria(i, d, op, parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("E2",11, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // E2 ::= E3 
            {
              Nodo RESULT =null;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = e; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("E2",11, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // E3 ::= E3 OP1 E4 
            {
              Nodo RESULT =null;
		Nodo i = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-2)).value;
		String op = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-1)).value;
		Nodo d = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = new ExpBinaria(i, d, op, parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("E3",12, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // E3 ::= E4 
            {
              Nodo RESULT =null;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = e; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("E3",12, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // E4 ::= E4 OP2 E5 
            {
              Nodo RESULT =null;
		Nodo i = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-2)).value;
		String op = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-1)).value;
		Nodo d = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = new ExpBinaria(i, d, op, parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("E4",13, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // E4 ::= E5 
            {
              Nodo RESULT =null;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = e; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("E4",13, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // E5 ::= OP3 E5 
            {
              Nodo RESULT =null;
		String op = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-1)).value;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 
         if (op.equals("&")) {
            RESULT = new ExpReferencia(e, parser.fila(0), parser.columna(0));
         } else {
            RESULT = new ExpUnaria(e, op, parser.fila(0), parser.columna(0)); 
         }
      
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("E5",14, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // E5 ::= MULT E5 
            {
              Nodo RESULT =null;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = new DesignadorPuntero(e, parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("E5",14, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // E5 ::= E6 
            {
              Nodo RESULT =null;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = e; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("E5",14, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // E6 ::= E6 CAP E0 CCIERRE 
            {
              Nodo RESULT =null;
		Nodo d = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-3)).value;
		Nodo idx = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-1)).value;
		 RESULT = new DesignadorArray((Designador)d, idx, parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("E6",15, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // E6 ::= E6 PUNTO IDENTIFICADOR 
            {
              Nodo RESULT =null;
		Nodo d = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-2)).value;
		String campo = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = new DesignadorCampo((Designador)d, campo, parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("E6",15, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // E6 ::= E7 
            {
              Nodo RESULT =null;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = e; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("E6",15, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // E7 ::= LIT 
            {
              Nodo RESULT =null;
		Nodo l = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = l; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("E7",16, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // E7 ::= IDENTIFICADOR 
            {
              Nodo RESULT =null;
		String id = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = new DesignadorVariable(id, parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("E7",16, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // E7 ::= PAP E0 PCIERRE 
            {
              Nodo RESULT =null;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-1)).value;
		 RESULT = e; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("E7",16, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // E7 ::= NEW T 
            {
              Nodo RESULT =null;
		Tipo t = (Tipo)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = new ExpNew(t, parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("E7",16, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // E7 ::= IDENTIFICADOR PAP P_LLAMADA PCIERRE 
            {
              Nodo RESULT =null;
		String id = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-3)).value;
		LinkedList<Nodo> args = (LinkedList<Nodo>)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.elementAt(CUP$AnalizadorSintacticoMilu$top-1)).value;
		 RESULT = new ExpLlamadaFuncion(id, args, parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("E7",16, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // LIT ::= INTNUM 
            {
              Nodo RESULT =null;
		String n = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = new ExpLiteral(n, "int", parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("LIT",17, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // LIT ::= FLOATNUM 
            {
              Nodo RESULT =null;
		String f = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = new ExpLiteral(f, "float", parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("LIT",17, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // LIT ::= TRUE 
            {
              Nodo RESULT =null;
		String t = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = new ExpLiteral("true", "bool", parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("LIT",17, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // LIT ::= FALSE 
            {
              Nodo RESULT =null;
		String f = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoMilu$stack.peek()).value;
		 RESULT = new ExpLiteral("false", "bool", parser.fila(0), parser.columna(0)); 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("LIT",17, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // OP0 ::= IGUAL 
            {
              String RESULT =null;
		 RESULT = "=="; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("OP0",26, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // OP0 ::= DISTINTO 
            {
              String RESULT =null;
		 RESULT = "!="; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("OP0",26, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // OP0 ::= MENOR 
            {
              String RESULT =null;
		 RESULT = "<"; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("OP0",26, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // OP0 ::= MAYOR 
            {
              String RESULT =null;
		 RESULT = ">"; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("OP0",26, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // OP0 ::= MENORIGUAL 
            {
              String RESULT =null;
		 RESULT = "<="; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("OP0",26, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // OP0 ::= MAYORIGUAL 
            {
              String RESULT =null;
		 RESULT = ">="; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("OP0",26, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // OP1 ::= SUMA 
            {
              String RESULT =null;
		 RESULT = "+"; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("OP1",27, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // OP1 ::= RESTA 
            {
              String RESULT =null;
		 RESULT = "-"; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("OP1",27, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // OP2 ::= MULT 
            {
              String RESULT =null;
		 RESULT = "*"; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("OP2",28, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // OP2 ::= DIV 
            {
              String RESULT =null;
		 RESULT = "/"; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("OP2",28, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // OP2 ::= MOD 
            {
              String RESULT =null;
		 RESULT = "%"; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("OP2",28, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // OP3 ::= NEG 
            {
              String RESULT =null;
		 RESULT = "!"; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("OP3",29, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // OP3 ::= RESTA 
            {
              String RESULT =null;
		 RESULT = "-"; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("OP3",29, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // OP3 ::= REF 
            {
              String RESULT =null;
		 RESULT = "&"; 
              CUP$AnalizadorSintacticoMilu$result = parser.getSymbolFactory().newSymbol("OP3",29, RESULT);
            }
          return CUP$AnalizadorSintacticoMilu$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$AnalizadorSintacticoMilu$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$AnalizadorSintacticoMilu$do_action(
    int                        CUP$AnalizadorSintacticoMilu$act_num,
    java_cup.runtime.lr_parser CUP$AnalizadorSintacticoMilu$parser,
    java.util.Stack            CUP$AnalizadorSintacticoMilu$stack,
    int                        CUP$AnalizadorSintacticoMilu$top)
    throws java.lang.Exception
    {
              return CUP$AnalizadorSintacticoMilu$do_action_part00000000(
                               CUP$AnalizadorSintacticoMilu$act_num,
                               CUP$AnalizadorSintacticoMilu$parser,
                               CUP$AnalizadorSintacticoMilu$stack,
                               CUP$AnalizadorSintacticoMilu$top);
    }
}

