
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon May 18 13:16:14 CEST 2026
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DISTINTO = 18;
  public static final int DE = 43;
  public static final int MULT = 12;
  public static final int CCIERRE = 28;
  public static final int BCIERRE = 30;
  public static final int PCIERRE = 26;
  public static final int RESTA = 11;
  public static final int CAP = 27;
  public static final int INT = 32;
  public static final int ARRAY = 35;
  public static final int INTNUM = 7;
  public static final int FOR = 41;
  public static final int REF = 16;
  public static final int BAP = 29;
  public static final int IDENTIFICADOR = 6;
  public static final int MENORIGUAL = 21;
  public static final int AND = 23;
  public static final int IGUAL = 17;
  public static final int OR = 24;
  public static final int BOOL = 33;
  public static final int COMMA = 3;
  public static final int DIV = 13;
  public static final int SUMA = 10;
  public static final int IF = 38;
  public static final int MAYORIGUAL = 22;
  public static final int EOF = 0;
  public static final int RETURN = 42;
  public static final int ASIG = 31;
  public static final int TRUE = 9;
  public static final int NEW = 45;
  public static final int error = 1;
  public static final int SCOLON = 5;
  public static final int FLOATNUM = 8;
  public static final int MENOR = 19;
  public static final int MOD = 14;
  public static final int VOID = 44;
  public static final int MAYOR = 20;
  public static final int PAP = 25;
  public static final int COLON = 4;
  public static final int NEG = 15;
  public static final int ELSE = 39;
  public static final int PUNTO = 47;
  public static final int READ = 49;
  public static final int WHILE = 40;
  public static final int FLOAT = 34;
  public static final int DEF = 37;
  public static final int FALSE = 50;
  public static final int AS = 2;
  public static final int STRUCT = 46;
  public static final int VAR = 36;
  public static final int PRINT = 48;
  public static final int FREE = 51;
}

